Make the README less hostile
jzelinskie/faq pull request #97
Opened 2021-12-22 22:41 UTC by CyberShadow

Attempts to fix issue #69.

- Word the paragraph such that a warning that an insult is incoming precedes the actual insult.
- Don't actually spell out the insult.
- Make it clear that the insult is not directed at the reader.
- Use a nice placeholder character to indicate that the insult is meant in jest, and not hostility.

2021-12-22 22:45 UTC, CyberShadow commented
More extreme alternatives:

- Remove the line, leaving readers to decide on their own on a pronunciation for tool's name that they are comfortable with.
- Rename the project, as `faq` is difficult to search online for anyway, due to the prevalence of the [pre-existing term](https://en.wikipedia.org/wiki/FAQ).

2021-12-23 06:07 UTC, jzelinskie requested changes
Hey there! Thanks for the PR!

I think this is an objective an improvement to communicating the spirit of the name of the project.

I'm also willing to consider your extreme suggestions as well if there is a proposal for a name sufficiently clever.

2021-12-23 12:19 UTC, CyberShadow commented on README.md
> +How do you pronounce faq? The same way you would insult a particularly nasty structured document: "F♥︎♥︎♥︎ You".
The usage text doesn't seem like the best place for a pronunciation guide, and probably not the place one would look should they be actually looking for one. How do you feel about removing the line from there?

2021-12-23 16:52 UTC, jzelinskie approved these changes

2021-12-23 16:59 UTC, merged